# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The white rabbit
email: info@thewhiterabbitonthepark.co.nz
description: > # this means to ignore newlines until "baseurl:"
  The White Rabbit on the park is a fine dining restaurant and bar on Victoria Park Market in downtown Auckland.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://musedivision.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
name: Patrick McCaffrey
markdown: kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]
